version: '3'
services:
    nginx:
        image: nginx:latest
        platform: linux/amd64
        ports:
            - "8084:80"
        volumes:
            - ./public:/var/www/html/public
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/amd64
        volumes:
            - .:/var/www/html
        environment:
            - "DB_HOST=db"
            - "DB_PORT=3306"
        depends_on:
            - db

    db:
        image: postgres:latest
        platform: linux/amd64
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
